import { TextContainers } from "./TextContainers";

export function PopUpContainer({
    purpose,
    dataArray,
    register,
    errors,
    handleSubmit,
    onSubmit,
    isLoading,
    error,
    errorText,
    completed,
    completedText,
    close,
    setStateAction
}){
    console.log(purpose)
    return(
        <div
            className="popup-container"
        >
            <TextContainers 
                purpose={purpose}
                textArray={dataArray}
                register={register}
                errors={errors}
                handleSubmit={handleSubmit}
                onSubmit={onSubmit}
                isLoading={isLoading}
                error={error}
                errorText={errorText}
                completed={completed}
                completedText={completedText}
                close={close}
                setState={setStateAction}
            />
        </div>
    )
}