"""create pillar products table

Revision ID: 102f0ea8ce03
Revises: 42e1de365f2b
Create Date: 2025-12-23 18:36:21.404927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102f0ea8ce03'
down_revision = '42e1de365f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pillar_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_pillar_products_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_pillar_products_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pillar_products')
    # ### end Alembic commands ###
