"""create pillars model

Revision ID: 10a207988841
Revises: 2a7d06d05d2a
Create Date: 2025-12-22 17:09:47.846931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a207988841'
down_revision = '2a7d06d05d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pillar')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pillars')
    # ### end Alembic commands ###
