"""create table connecting pillars and sustainable goals

Revision ID: 1603db386460
Revises: c60407c400d9
Create Date: 2026-01-20 15:09:36.630654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1603db386460'
down_revision = 'c60407c400d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pillar_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=True),
    sa.Column('sustainable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_pillar_goals_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['sustainable_id'], ['sustainability_goals.id'], name=op.f('fk_pillar_goals_sustainable_id_sustainability_goals')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pillar_goals')
    # ### end Alembic commands ###
