"""create member teams table

Revision ID: 2a7d06d05d2a
Revises: 6730469df754
Create Date: 2025-12-22 15:34:52.726930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7d06d05d2a'
down_revision = '6730469df754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['team_members.id'], name=op.f('fk_member_teams_member_id_team_members')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_member_teams_team_id_teams')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_teams')
    # ### end Alembic commands ###
