"""update pillar sustainability model

Revision ID: 843a96dceada
Revises: f0252c9a7be9
Create Date: 2026-01-26 21:51:00.773179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843a96dceada'
down_revision = 'f0252c9a7be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pillar_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pillar_goals', schema=None) as batch_op:
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###
