"""update intro model

Revision ID: c9e28a5f46a6
Revises: 7cbe9138c828
Create Date: 2025-12-22 23:01:01.077497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e28a5f46a6'
down_revision = '7cbe9138c828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('introduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('bg_img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('introduction')
    # ### end Alembic commands ###
